### ISSUE TITLE
Can not debug remotely.

### ISSUE THREAD

**Issue by hieu-lai** [expo/react-native-appearance#1]
I bumped into this error while trying to debug remotely. 
![Screen Shot 2019-09-04 at 11 34 05 am](https://user-images.githubusercontent.com/21213601/64219833-7e791d80-cf0a-11e9-9105-876fda8f00e8.png)

The library works fine when remote debugging is turned off.
"react": "16.8.3"
"react-native": "^0.59.6"

**Comment by brentvatne** [comment]
not much we can do about this, this is a limitation with debugging in chrome and sync methods in react-native.

**Comment by brentvatne** [comment]
i'll leave this open for other folks

**Comment by brentvatne** [comment]
fixed this by removing sync method
