### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by archieherbias** [expo/react-native-appearance#11]
I have create a project using `expo init` and then ejected from it. I installed this package using `yarn add react-native-appearance` and run `react-native link react-native-appearance`. 

I tried importing `import { Appearance } from "react-native-appearance";`
But when I run the ios app `yarn ios` it says:
```
null is not an object (evaluating 'NativeAppearance.initialPreferences')

<unknown>
    polyfill.tsx:15:68
loadModuleImplementation
    require.js:331:6
<unknown>
    index.tsx:9:24
loadModuleImplementation
    require.js:331:6
<unknown>
    App.js:3
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:2
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0
```

## Simulator
OS - ios 13.1
Simulator - iPhone X

## Dependencies installed
```
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-appearance": "^0.1.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-unimodules": "~0.5.4",
    "react-native-web": "^0.11.7"
```

**Comment by Monte9** [comment]
I ran into the same issue. I am on the same RN version as @archieherbias 😅

> "react-native": "0.59.10"

Let me know if you find a fix! Not a blocker for me right now.

**Comment by sorter** [comment]
I am running into this issue also.

>        "react-native": "0.60.5",

**Comment by jezzdk** [comment]
I have the same issue

**Comment by sorter** [comment]
I solved this problem with the following:

```
cd ios
pod install
```

**Comment by ab9st8** [comment]
same issue here :/

**Comment by KenPet11** [comment]
same issue, still can't find a fix

**Comment by brentvatne** [comment]
you should follow the instructions that are in the readme for expo projects. run `expo install react-native-appearance`. also see https://docs.expo.io/versions/v35.0.0/sdk/appearance/

**Comment by KenPet11** [comment]
@brentvatne I have followed that documentation, many times, and I am still getting the same error. Curious if anyone has had this work  ^

**Comment by brentvatne** [comment]
please share a minimal reproducible example project @KenPet11

**Comment by RaquelCasadoDias** [comment]
I have the same problem... I'm working with react-native: 0.59.10. OS ios 13.0 Simulator: iphone 11 Pro Max. Does anyone have a fix?

**Comment by brentvatne** [comment]
the fix is to link the native code ;)

i'm locking this thread but if anyone wants to create a new issue with a reproducible example as i requested we can certainly look into it.
