### ISSUE TITLE
Cannot find module 'react-native-appearance' 

### ISSUE THREAD

**Issue by Noitham** [expo/react-native-appearance#12]
When running a jest test on a file containing the import of the package I'm getting the following error:

```
'Cannot find module 'react-native-appearance'

You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'js', 'json', 'node'].
```

After adding 'tsx' as a moduleFileExtensions:

```
.../react-native-appearance/src/index.tsx:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';

SyntaxError: Cannot use import statement outside a module
```

Has someone else faced the same issue?

"react-native": "0.60.5",
"jest": "24.9.0",
"ts-jest": "^24.0.2",

**Comment by alexborton** [comment]
I am also getting a similar issue when trying to run Jest.. has killed all my tests for Native :(

For now, i have added `tsx` as a `moduleFileExtensions` and mocked the module to return a function in my setup.js; 

```
jest.mock('react-native-appearance', () => ({
  useColorScheme: jest.fn(),
}))
```

**Comment by brentvatne** [comment]
pr welcome to make this easier for people, but also mocking it seems fine

**Comment by SpawnAtis** [comment]
@brentvatne  I got `Cannot find module 'react-native-appearance'` when I import it in Component.tsx

"react-native-appearance": "^0.2.1",
"typescript": "^3.7.2"

`tsconfig.json`:
```js
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "@src/*": ["src/*"]
    },
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "allowJs": true,
    "checkJs": false,
    "declaration": false,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "jsx": "preserve",
    "lib": ["dom", "es2017", "esnext.array"],
    "skipLibCheck": true,
    "types": ["jest"],
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "pretty": true,
    "removeComments": true,
    "sourceMap": true,
    "allowUnreachableCode": false,
    "noImplicitAny": false
  },
  "include": ["src", "typings"],
  "exclude": ["node_modules"]
}
```

**Comment by brentvatne** [comment]
sounds like an issue with your tsconfig but i do not know what the problem is, maybe you can work backwards from a tsconfig that works to see which of your settings is problematic

**Comment by SpawnAtis** [comment]
@brentvatne hmm... It is strange, because all other vendors are imported correctly. I noticed that only ``react-native-appearance`` uses ``index.native.tsx`` as entry file.  I think, it is related with ``typescript-eslint `` configuration. May be it can not parse such file extension ?🤔 

.eslintrc

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    //tsconfigRootDir: './',
    //project: './tsconfig.json',
    ecmaVersion: 2018,
    ecmaFeatures: {
      jsx: true,
    },
    sourceType: 'module',
    //extraFileExtensions: ['.native.tsx'],
  },
  plugins: ['@typescript-eslint'],
  extends: [
    'kentcdodds',
    'kentcdodds/react',
    'kentcdodds/jsx-a11y',
    'kentcdodds/jest',
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'plugin:import/typescript',
  ],
  settings: {
    react: {
      version: 'detect',
    },
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
      node: {
        moduleDirectory: ['node_modules', 'src/', 'typings/'],
      },
    },
  },
 rules: { ... }
}
```
P.S. When I downgrade to 0.1.0 . this error disappeared, but  I have this [https://github.com/expo/react-native-appearance/issues/5](5)

**Comment by brentvatne** [comment]
@SpawnAtis - that makes sense! we should probably have just `index.tsx` and `index.web.tsx` in that case

**Comment by brentvatne** [comment]
@SpawnAtis - try 0.2.2, hopefully that will resolve your issue

**Comment by SpawnAtis** [comment]
@brentvatne Yeah! Great 👍. Thx
