### ISSUE TITLE
Appearance.getColorScheme() returns 'no-preference' on appcenter builds

### ISSUE THREAD

**Issue by nschild** [expo/react-native-appearance#13]
Hello,
Does anyone else have this issue?

I am calling Appearance.getColorScheme() and getting no-preference 
It works correctly on debug builds, but with builds built on AppCenter, it is not.

React Native 0.59.2
iPhone XR - iOS 13.2b4

Some psuedo code:

index.js

    import { AppRegistry } from 'react-native';
    import App from './app';
    import { name as appName } from './app.json';

    const appRoot = App;
    AppRegistry.registerComponent(appName, () => appRoot);

app.tsx

    import { Component } from 'react';
    import { Appearance, AppearanceProvider } from 'react-native-appearance';
    import ReactNativeRestart from 'react-native-restart';
    import { Text, Alert } from 'react-native';

    interface AppProps {}

    export default class App extends Component<AppProps> {
      componentDidMount(){
        Appearance.addChangeListener(() => {
            ReactNativeRestart.Restart();
        });
        setInterval(() => {
            Alert.alert(Appearance.getColorScheme());
        }, 1000);
      }
      render() {
        return <AppearanceProvider><Text> Hello World</Text></AppearanceProvider>;
      }
    }

**Comment by anhtuank7c** [comment]
@nschild Man, dark mode supported on  iOS 13+, android 10+
The lower operating system will get `no-preference`, your case is version ` iOS 11.2b4`

**Comment by nschild** [comment]
@anhtuank7c Sorry, that was a typo on my part. I meant to say 13.2b4.

**Comment by brentvatne** [comment]
you might need to set this key in your Info.plist - https://developer.apple.com/documentation/bundleresources/information_property_list/uiuserinterfacestyle

**Comment by nschild** [comment]
@brentvatne From what I can tell, _UIUserInterfaceStyle_ overrides the user's preference of Light/Dark mode. I would like to detect what they want to use.

**Comment by brentvatne** [comment]
set it to `Automatic`

**Comment by nschild** [comment]
@brentvatne 
Thanks for the update, although, I am getting the same result:

_ios/{appname}/Info.plist_

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
        <dict>
            ...
            <key>UIUserInterfaceStyle</key>
            <string>Automatic</string>
        </dict>
    </plist>

**Comment by brentvatne** [comment]
if you share a minimal reproducible example we can look into it but i am unable to reproduce this in any of my projects

**Comment by nschild** [comment]
Closed. Turns out Appcenter was set to build with Xcode 8. Updating it to Xcode 11 works.
