### ISSUE TITLE
com.reactlibrary package name issue

### ISSUE THREAD

**Issue by gaodeng** [expo/react-native-appearance#15]
./gradlew assembleRelease

java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.reactlibrary.BuildConfig

**Comment by brentvatne** [comment]
hi! share a reproducible example please, maybe you have some other package with the same package name?

**Comment by gaodeng** [comment]
Indeed it is. I am using react-native-threads https://github.com/joltup/react-native-threads 。
Renaming one of these two libraries solves the problem

**Comment by brentvatne** [comment]
renamed the package to io.expo.appearance in 0.3.0 to avoid clashes
