### ISSUE TITLE
Feat: Get if system supports dark color scheme

### ISSUE THREAD

**Issue by thiagoferolla** [expo/react-native-appearance#17]
Dark mode is a feature present only on the latest versions of android and ios (aka. android 10 and ios 13).

Currently the library returns 'no-preference' when used in older versions but it would be great if we could detect if the system supports the dark color scheme or not. It would be especially helpful in a scenario where I want to offer a dark mode for my app with a manual toggle or an option to automatically toggle based on the system (and thsi option shouldn't appear when the system doesn't support it).

I would be glad to help  implement it.

**Comment by brentvatne** [comment]
you can implement this in js by using the `Platform` module and checking the version of the OS :)

https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.ios.js
https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.android.js

if you write a function for this and want to add it to the README that'd be cool!
