### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by thiagoferolla** [expo/react-native-appearance#2]
Android 10 was reently released with dark theme support like iOS 13.

Is their any plans to also support android?

**Comment by brentvatne** [comment]
yeah we will add this soon

**Comment by minhvuongrbs** [comment]
Nice, i will comment here to be informed of your great work

**Comment by NTag** [comment]
Can't wait for it!

**Comment by unimonkiez** [comment]
Can't wait!

**Comment by anhtuank7c** [comment]
I am testing it now. Will have PR soon.

**Comment by anhtuank7c** [comment]
@brentvatne Please review my [PR](https://github.com/expo/react-native-appearance/pull/10)
May contains some different in `TypeScript` code but the native one run smoothly already.

**Comment by anhtuank7c** [comment]
You guys can install the latest module which already supports `Android 10` and `iOS 13` right here.

`yarn add react-native-appearance@https://github.com/anhtuank7c/react-native-appearance.git`
and follow along with [`README`](https://github.com/anhtuank7c/react-native-appearance#mostly-automatic-install-with-react-native) to install `pod`, config `Android`

**Comment by brentvatne** [comment]
see readme on master, this is now supported thanks to @anhtuank7c!

you will need to install 0.2.0-rc.0 and follow the android linking and config instructions
