### ISSUE TITLE
Can this package only be used from typescript?

### ISSUE THREAD

**Issue by benadamstyles** [expo/react-native-appearance#20]
When I install this package, I only get `ts` and `tsx` files in `node_modules/react-native-appearance`, and various tools (e.g. ESLint) throw errors like `Unable to resolve path to module 'react-native-appearance'`.

Can this package only be used in typescript projects?

**Comment by brentvatne** [comment]
try installing 0.2.2. react-native supports ts and tsx extensions out of the box so that shouldn't be an issue, it will just strip out the type annotations

**Comment by benadamstyles** [comment]
Thanks, it does work fine but it breaks `eslint-plugin-import` still, and completely breaks Flow, which has been so far the recommended type system for React Native. It's a shame to have to ignore this import from these tools. I understand the desire to avoid a compile step but the small cost of running a `tsc` in your release flow would make it a lot easier to use this in non-TS projects.

Needless to say I'm very happy to help put this into place if it's a route you're happy with.

**Comment by brentvatne** [comment]
@benadamstyles - that would be great if you could! can you use https://github.com/react-native-community/bob to configure it?

**Comment by brentvatne** [comment]
release 0.3.0 which uses bob so this should not be an issue anymore
