### ISSUE TITLE
null is not an object (evaluating '_NativeAppearance.NativeAppearance.initialPreferences')

### ISSUE THREAD

**Issue by christinehesher** [expo/react-native-appearance#21]
**UPDATE: THE REASON IT WAS NOT WORKING IS THAT MY SDK VERSION WAS 34 AND THE PACKAGE NEEDS IT TO BE ^35.** But I'm gonna leave it here anyways in case someone as dumb as me ever has the same issue.

My app is bootstrapped via expo and I am struggling to get platform theme. I installed the package using **expo install react-native-appearance** and put **"userInterfaceStyle": "automatic"** under expo > ios in app.json. But when I try to import the library I get the following error:

```
null is not an object (evaluating 'NativeAppearance.initialPreferences')

<unknown>
    polyfill.tsx:14:68
loadModuleImplementation
    require.js:331:6
<unknown>
    index.tsx:9:24
loadModuleImplementation
    require.js:331:6
<unknown>
    App.js:11
loadModuleImplementation
    require.js:331:6
<unknown>
   AppEntry.js:4
loadModuleImplementation
   require.js:331:6
guardedLoadModule
   require.js:197:45
global code
<unknown file>:0
```

I know this question has been asked before but the only suggestion was to run react-native link, which is not helping since I'm using expo (although I've tried this solution too). 
These are the dependencies in my project:

```
"dependencies": {
    ...
    "expo": "^34.0.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-appearance": "^0.2.2",
    ...
}
```

Please help!

**Comment by brentvatne** [comment]
thanks for the followup, i'll close the issue because it can still be found while closed :)

**Comment by oillada** [comment]
Hi, I'm getting this same error only in the Android simulator, in iOS device and simulator works great, can you help me?

**Comment by brentvatne** [comment]
@oillada - make sure you're on sdk36.

**Comment by solace** [comment]
On expo bare (expo init minimal no typescript) with SDK 36 only adding the AppearanceProvider, I get this issue on Android simulator and a tethered Android device.

Update: Manually linking Android resolves this issue.

**Comment by a-polishchuk** [comment]
@solace hi, please advice, which exact dependencies I should link manually? I've ejected expo app, have many different dependencies. Looking at settings.gradle file, should I add here something like 
`include ':react-native'
project(':react-native').projectDir = new File(rootProject.projectDir, '../node_modules/react-native/android')` ?

**Comment by solace** [comment]
@polishchukandrey 

Follow the repo readme "Manually link the library on Android" section.

**Comment by a-polishchuk** [comment]
> @polishchukandrey
> 
> Follow the repo readme "Manually link the library on Android" section.

Thanks a lot!

**Comment by santiagoalmeidabolannos** [comment]
```
cd ios
pod install
```
works for me

**Comment by SeanRenet** [comment]
I am having this issue with a react native bare install using:
"expo": "~38.0.9",
"react-native-unimodules": "~0.10.1",
"react-native-appearance": "^0.3.4",

**Comment by adnan1naeem** [comment]
Hi i am facing same error with expo "39.0.3" in expo ejected project.
