### ISSUE TITLE
Unable to force light mode to datepicker component.

### ISSUE THREAD

**Issue by RiseOoi** [expo/react-native-appearance#24]
Bug Report:

See the original discussion: https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/320

Ideally, when using Appearance, we should be able to force light mode to ALL components.

Yet, after forcing light mode with Appearance, it seems that NOT ALL components render everything in light mode.

In this case, the modal's text is rendered in Dark Mode (according to phone's setting) instead of the forced light mode by Appearance.

**Comment by mmazzarolo** [comment]
FYI @Riseley , as far as I know, SDK36 will include the new community datetime-picker.

**Comment by RiseOoi** [comment]
@mmazzarolo, I am aware of that. Have you tried using the new datetime-picker? Does the problem persist?

**Comment by Riseley** [comment]
@mmazzarolo, I am aware of that. Have you tried using the new datetime-picker? Does the problem persist?

**Comment by mmazzarolo** [comment]
@Riseley it's working fine (still has a couple of issues) but I haven't tried it within expo.

**Comment by RiseOoi** [comment]
Thanks, I will try to use it within expo and see if it works properly. Closing the issue because it will resolve itself for this particular component. (But not sure if the bug persists to other components)
