### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ahmetozalp** [expo/react-native-appearance#26]
Hello I constantly get the following error while build in latest version,

`> Configure project :react-native-appearance
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.`

**Comment by solace** [comment]
It's a warning not an error. But yes, seeing this issue as well using 0.3.1.

**Comment by jose920405** [comment]
hi @solace 

This problem still happened to me in Version: `0.3.3`
