### ISSUE TITLE
Appearance always says "light" regardless of what the theme actually is

### ISSUE THREAD

**Issue by rmonaghanjr** [expo/react-native-appearance#3]
Hello,

As the title says, the theme always says light. I'm using the example code provided by expo, and it isn't working... why isn't it?

iOS 13.1

**Comment by sandersonsoares** [comment]
The same problem occurs with me.

**Comment by rmonaghanjr** [comment]
u/brentvatne said to me on a Reddit thread, 

> sorry i will improve docs around this tomorrow. in app.json under the `ios` key add "userInterfaceStyle": "automatic"

And although I haven’t tested it yet, it should fix the issue

**Comment by NTag** [comment]
It fixed the issue for me, thanks 🙏 !
