### ISSUE TITLE
React Native's SegmentedControlIOS colour

### ISSUE THREAD

**Issue by darrylyoung** [expo/react-native-appearance#37]
Hi, everyone,

I recently started using this package when adding a theme to my app (based on React Navigation's Theme [documentation](https://reactnavigation.org/docs/en/themes.html)). It's working fine but I've noticed an issue with React Native's `SegmentedControlIOS` component and I don't know if it's an issue with this package, React Navigation, or with that component itself.

As I haven't yet written my dark theme, I set my app to display the light theme regardless of whether the device was in dark mode or not. For the sake of testing, my _custom_ light theme just consisted of the default values recommended, i.e. `primary`, `background`, etc. This meant that nothing should have changed (visually) when switching my phone between light and dark mode.

What I noticed, though, is that the `SegmentedControlIOS` still changed its appearance when the phone was set to dark mode. Here are screenshots to show what I mean.

_**Light mode**_
![light-mode](https://user-images.githubusercontent.com/1460800/74936007-a3464c00-53e9-11ea-9534-87797289f169.png)

_**Dark mode**_
![dark-mode](https://user-images.githubusercontent.com/1460800/74936027-ae00e100-53e9-11ea-9d7e-eb0cb7d0ea2f.png)

I don't understand why this is changing. I have no custom styles and the component doesn't seem to change if I manually try to adjust `tintColor`. Is there any other way I can control this?

Apologies if this is an issue in React Navigation or in React Native itself; I just wasn't sure where to start. Thanks!

**Comment by Naturalclar** [comment]
@darrylyoung :wave: I believe this is an issue with react-native core itself.
It's fixed in this issue https://github.com/facebook/react-native/pull/27643, but the fix is not included in the latest published version of react native.
If you're using bare workflow and not expo, you can also try using the [community repo](https://github.com/react-native-community/segmented-control) which is more up to date :)

**Comment by darrylyoung** [comment]
Hi, @Naturalclar. 👋

Thank you for your comment. Unfortunately, I'm using Expo. As I couldn't originally find a way around this I've taken the `SegmentedControlIOS` out of my app completely. Maybe, once the fix is in a React Native release (and then in Expo), I can look at it again. No worries.

Thanks again. Have a nice day.
