### ISSUE TITLE
Cannot read property 'initialPreferences' of undefined - Jest test

### ISSUE THREAD

**Issue by DwCleb** [expo/react-native-appearance#38]
I'm using this library and working nice in the App. But when I try run the tests (using jest and react test renderer) the console plot the follow error:

![Screenshot 2020-02-24 at 11 09 10](https://user-images.githubusercontent.com/30187750/75147822-1c011d00-56f6-11ea-8505-77919a39f8bb.png)

**Comment by lissau** [comment]
Same issue here.

Attempted to mock it:

    // __mocks__/react-native-appearance.js

    jest.mock('react-native-appearance', () => {
	return {};
    });`

But got `TypeError: Cannot read property 'getColorScheme' of undefined` instead. Mocking that function doesn't solve the problem either. Probably i'm not mocking it correctly

**Comment by DwCleb** [comment]
@lissau  I solved this issue.

Follow above what I need did:

```

import { Button, Icon } from '~/components';
import { Props as ButtonProps } from '~/components/Button';
import { ThemeProvider } from 'styled-components/native';
import darkTheme from '~/theme/ThemeContext/dark';
import lightTheme from '~/theme/ThemeContext/light';

jest.mock('react-native-appearance', () => ({
  theme: jest.fn(),
}));
const onClick = jest.fn();
let wrapper = {};
let props: ButtonProps = { title: 'Test', onPress: onClick, iconDirection: 'start', variant: 'pay' };
let theme = lightTheme.theme;

describe('<Button />', () => {
  beforeAll(() => {
    jest.useFakeTimers();
  });

  beforeEach(() => {
    wrapper = create(
      <ThemeProvider theme={theme}>
        <Button {...props} />
      </ThemeProvider>
    );
    return wrapper;
  });
  it('renders correctly in Light Theme', () => {
    props = { ...props, ...{ iconName: 'add', iconDirection: 'end' } };
    expect(wrapper).toMatchSnapshot();
  });
});
```

The ThemeProvider is required to use props.theme in styled components.

I hope help someone!

**Comment by lissau** [comment]
Thanks for the quick reply @DwCleb 

Actually, I found a mock in the module, so all I did was:

    // __mocks__/react-native-appearance.js
    export * from 'react-native-appearance/src/mock';

Thank again

**Comment by ys-sherzad** [comment]
@lissau hi there, then how to use them, the mocks, I am having a similar problem

<img width="785" alt="Screen Shot 2020-11-28 at 15 44 18" src="https://user-images.githubusercontent.com/55835805/100523616-71abae00-31cf-11eb-9cbf-c8957f37bbc2.png">

I am trying to test  a custom `Button` component
In this component, I have a custom hook `const { theme } = useTheme()`
the hook is simply getting `theme` from reducer
`useTheme`
```
const useTheme = () => {

    const dispatch = useDispatch();

    const { theme } = useSelector(
        (state: RootState) => state.app
    );

    const toggleTheme = useCallback(
        () => {
            dispatch(setTheme({ theme: theme.$mode === 'dark' ? themes.light : themes.dark }))
        },
        [theme]
    );

    return { theme, toggleTheme };
};

export default useTheme;
```
the error points way down in the reducer
```
'use strict';

import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { AppState, Theme } from '../types';
import { themes } from '../utils/theme';
import { Appearance } from 'react-native-appearance';   <-- the error is pointing here

/**
 * take system's mode preference
 */
const systemTheme = Appearance.getColorScheme(); 

/**
 * 
 * @param mode light | dark | no-preference
 * @returns [Theme]
 */
const getSystemTheme = (mode: 'light' | 'dark' | 'no-preference') => {
    if (mode === 'no-preference' || mode === 'light') return themes.light;
    return themes.dark;
}

/**
 * set initial state for theme
 */
const initialState: AppState = {
    theme: getSystemTheme(systemTheme)
}

// code omitted
```

**Comment by damii** [comment]
> @lissau hi there, then how to use them, the mocks, I am having a similar problem
> 
> <img alt="Screen Shot 2020-11-28 at 15 44 18" width="785" src="https://user-images.githubusercontent.com/55835805/100523616-71abae00-31cf-11eb-9cbf-c8957f37bbc2.png">
> 
> I am trying to test a custom `Button` component
> In this component, I have a custom hook `const { theme } = useTheme()`
> the hook is simply getting `theme` from reducer
> `useTheme`
> 
> ```
> const useTheme = () => {
> 
>     const dispatch = useDispatch();
> 
>     const { theme } = useSelector(
>         (state: RootState) => state.app
>     );
> 
>     const toggleTheme = useCallback(
>         () => {
>             dispatch(setTheme({ theme: theme.$mode === 'dark' ? themes.light : themes.dark }))
>         },
>         [theme]
>     );
> 
>     return { theme, toggleTheme };
> };
> 
> export default useTheme;
> ```
> 
> the error points way down in the reducer
> 
> ```
> 'use strict';
> 
> import { createSlice, PayloadAction } from '@reduxjs/toolkit';
> import { AppState, Theme } from '../types';
> import { themes } from '../utils/theme';
> import { Appearance } from 'react-native-appearance';   <-- the error is pointing here
> 
> /**
>  * take system's mode preference
>  */
> const systemTheme = Appearance.getColorScheme(); 
> 
> /**
>  * 
>  * @param mode light | dark | no-preference
>  * @returns [Theme]
>  */
> const getSystemTheme = (mode: 'light' | 'dark' | 'no-preference') => {
>     if (mode === 'no-preference' || mode === 'light') return themes.light;
>     return themes.dark;
> }
> 
> /**
>  * set initial state for theme
>  */
> const initialState: AppState = {
>     theme: getSystemTheme(systemTheme)
> }
> 
> // code omitted
> ```

i have same issue did you solve this?
