### ISSUE TITLE
How does Appearance.addChangeListener work?

### ISSUE THREAD

**Issue by annjawn** [expo/react-native-appearance#40]
I am not sure i can get it to work. I did `Appearance.addChangeListener` in my `componentDidMount` and have a state update inside of it but when I change the theme while testing nothing really happens and the `colorScheme` continues to have the previous `colorScheme` value. I am not sure if I am doing this correctly.

```js
componentDidMount(){
   this._schemeSubscription = Appearance.addChangeListener(({ colorScheme }) => {
            this.setState({ colorscheme: colorScheme });
        });
}
```

**Comment by abeeralshaer** [comment]
> I am not sure i can get it to work. I did `Appearance.addChangeListener` in my `componentDidMount` and have a state update inside of it but when I change the theme while testing nothing really happens and the `colorScheme` continues to have the previous `colorScheme` value. I am not sure if I am doing this correctly.
> 
> ```js
> componentDidMount(){
>    this._schemeSubscription = Appearance.addChangeListener(({ colorScheme }) => {
>             this.setState({ colorscheme: colorScheme });
>         });
> }
> ```

@annjawn How did you manage to fix it?

**Comment by annjawn** [comment]
I missed wrapping the root with `<AppearanceProvider>` , once I did that the `Appearance.addChangeListener` started working.

**Comment by AmirDoreh** [comment]
with the new  `useColorScheme()` there is no need for setting state any more, 
just use `const colortheme= useColorScheme()` and use colortheme anywhere

**Comment by aymkin** [comment]
What is I need to find color scheme outside the functional component?
