### ISSUE TITLE
Appearance does not change to dark mode

### ISSUE THREAD

**Issue by DingChenyu** [expo/react-native-appearance#43]

**Comment by DingChenyu** [comment]
useColorScheme() always returns ‘light’

**Comment by RoninSTi** [comment]
I'm having the same issue with Android, IOS works fine.

**Comment by DingChenyu** [comment]
> I'm having the same issue with Android, IOS works fine.
How is your IOS configured? Android is working.

**Comment by DingChenyu** [comment]
@RoninSTi  How is your IOS configured? Android is working.

**Comment by DingChenyu** [comment]
@RoninSTi  
Install、Linking、Configuration, this has been done by following the steps.
but is not working.

**Comment by darapsas** [comment]
I can approve, react-native-appearance useColorSchema() always returns 'light', tested on expo 37sdk project (android device, unfortunately I cannot test it on ios device).

react-native-appearance@3.3.0

**Comment by DingChenyu** [comment]
https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13 
<key>UIUserInterfaceStyle</key>
<string>Dark</string> (Light)

**Comment by DingChenyu** [comment]
In Info.plist
`<key>UIUserInterfaceStyle</key>`
`<string>Automatic</string>`

**Comment by darapsas** [comment]
I am on the expo managed flow project, so I don't have the convinience of editting those files.

**Comment by DingChenyu** [comment]
@Darapsas  Thank you. I have solved the problem.

**Comment by Joshuabaker2** [comment]
For others who stumble onto this issue, the fix if you are in Expo is that you need to add `"expo": {"userInterfaceStyle": "automatic"}` to your `app.json`

**Comment by destinybonavita** [comment]
> For others who stumble onto this issue, the fix if you are in Expo is that you need to add `"expo": {"userInterfaceStyle": "automatic"}` to your `app.json`

To add on to this; after adding `"userInterfaceStyle": "automatic"` to your `app.json`, you need to manually reload your app if you're coding in Expo for the change to take affect.
