### ISSUE TITLE
`tsc` error when `--isolatedModules` flag is provided

### ISSUE THREAD

**Issue by garethperky** [expo/react-native-appearance#5]
Using this with typescript works fine so long as you are not using the --isolatedModules flag. The moment that is set to true I get the following three typescript errors:

```
node_modules/react-native-appearance/src/index.tsx:21:3 - error TS1205: Cannot re-export a type when the '--isolatedModules' flag is provided.

21   ColorSchemeName,
     ~~~~~~~~~~~~~~~

node_modules/react-native-appearance/src/index.tsx:22:3 - error TS1205: Cannot re-export a type when the '--isolatedModules' flag is provided.

22   AppearanceListener,
     ~~~~~~~~~~~~~~~~~~

node_modules/react-native-appearance/src/index.tsx:23:3 - error TS1205: Cannot re-export a type when the '--isolatedModules' flag is provided.

23   AppearancePreferences,
```

It would be great if this were updated to include support for the isolatedModules flag! Thank you and please let me know if I can provide any further information!

**Comment by brentvatne** [comment]
maybe we need to ship a compiled build to handle this, pr welcome

**Comment by denkristoffer** [comment]
Expo's web support uses Next.js, which requires `isolatedModules: true`, so that's incompatible with `react-native-appearance` at the moment.

**Comment by colinyoung** [comment]
@denkristoffer  @brentvatne this was affecting me today, just +1'ing a hope for a fix.

I am not sure how to make a compiled build but would be happy to help write that PR if I can be pointed in the right direction.

**Comment by brentvatne** [comment]
@colinyoung -  if someone wants to set up https://github.com/react-native-community/bob on this project it'd be great!

**Comment by ericp3reira** [comment]
I solve that by exporting everything from `Appearance.types` in `index` so TS does not identify as double exports.

Here is the PR: https://github.com/expo/react-native-appearance/pull/19.

**Comment by brentvatne** [comment]
thanks @ericp3reira!

**Comment by ericp3reira** [comment]
Glad to help @brentvatne. 😄
